on:
  pull_request:
    types: [opened]
  push:

jobs:
  default:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macOS-13
          - os: macOS-latest
          - os: windows-latest
          - os: ubuntu-latest
            container:
              image: ubuntu:18.04
            extrasetup: |
              apt-get update -qqq
              apt-get install -y curl build-essential git
    steps:
      - uses: iffy/checkoutnodeps@master
      - uses: ./
